name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-2022
    env:
      VULKAN_SDK: C:\VulkanSDK\
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'true'
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        cache: true
    - name: build for release check
      run: D:\a\rt_core\rt_core\core3\build.bat Release On Off
    - name: build for debug check
      run: D:\a\rt_core\rt_core\core3\build.bat Debug On Off